### ISSUE TITLE
events.js unhandled error event

### ISSUE THREAD

**Issue by jondcallahan** [sindresorhus/speed-test#26]
Started getting an error today on multiple machines
```events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:465:22)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:43:22
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:226:13
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:493:16)
    at Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:534:19)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:224:9
```

Tried using node 5.0.0, 4.2.2 and 0.12.7 and received the same error.

**Comment by jondcallahan** [comment]
Which is a bummer as I used this tool multiple times a week :pensive: , used to work great!

**Comment by SamVerschueren** [comment]
It has something to do with [speedtest-net](https://github.com/ddsol/speedtest.net) what is used by this module. You should create an issue there.

**Comment by jondcallahan** [comment]
This issue appears to have been resolved.
