### ISSUE TITLE
Cannot read property 'settings' of null

### ISSUE THREAD

**Issue by gonchs** [sindresorhus/speed-test#39]
```
➜  ~ speed-test --version
1.7.0
➜  ~ speed-test

      Ping ⠇
  Download
    Upload
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:522:20)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:48:16
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:238:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:494:16)
    at Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:535:19)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:236:5
```

Fix possible by upgrading github.com/ddsol/speedtest.net dependency to v1.2.7

**Comment by sindresorhus** [comment]
> Fix possible by upgrading github.com/ddsol/speedtest.net dependency to v1.2.7

That happens automatically if you install / reinstall.
