### ISSUE TITLE
TypeError: Cannot read property 'settings' of null

### ISSUE THREAD

**Issue by crucialfelix** [sindresorhus/speed-test#41]
speed-test
```

      Ping ⠼
  Download
    Upload
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:522:20)
    at /Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:48:16
    at /Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:238:7
    at Parser.<anonymous> (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.exports.Parser.Parser.parseString (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:494:16)
    at Parser.parseString (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:535:19)
    at /Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:236:5
```

version 1.7.0

**Comment by kevva** [comment]
https://github.com/sindresorhus/speed-test/issues/39
