### ISSUE TITLE
Got this issue

### ISSUE THREAD

**Issue by MattixNow** [sindresorhus/speed-test#60]
```
$ speed-test

       Ping \
   Download
     Upload
× Error: Invalid character in entity name
Line: 61
Column: 40
Char:
    at error (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\sax\lib\sax.js:677:7)
    at SAXParser.write (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\sax\lib\sax.js:1491:13)
    at Parser.exports.Parser.Parser.parseString (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\xml2js\lib\parser.js:325:31)
    at Parser.parseString (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\xml2js\lib\parser.js:5:59)
    at exports.parseString (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\xml2js\lib\parser.js:361:19)
    at C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\speedtest-net\index.js:291:5
    at C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\speedtest-net\index.js:97:16
    at IncomingMessage.<anonymous> (C:\Users\Mattaio\AppData\Roaming\npm\node_modules\speed-test\node_modules\speedtest-net\index.js:167:7)
    at IncomingMessage.emit (events.js:203:15)
```

**Comment by sindresorhus** [comment]
Would be great if you could move this issue over to https://github.com/ddsol/speedtest.net as that's where the error is coming from.
