### ISSUE TITLE
`URL is not a constructor` when using --verbose

### ISSUE THREAD

**Issue by nvaken** [sindresorhus/speed-test#61]
```
$ speed-test --verbose

       Ping ⠧
   Download
     Upload
     Server
   Location
   Distance
/usr/local/lib/node_modules/speed-test/cli.js:93
        server.host = new URL(server.url).host;
                      ^

TypeError: URL is not a constructor
    at map (/usr/local/lib/node_modules/speed-test/cli.js:93:16)
    at EventEmitter.st.once.server (/usr/local/lib/node_modules/speed-test/cli.js:108:12)
    at EventEmitter.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at startDownload (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:708:10)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:685:7
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:388:11
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:118:16
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:353:16
```

**Comment by sindresorhus** [comment]
Looks like you're on an old Node.js version. Try upgrading.
