### ISSUE TITLE
not working in google cloud shell

### ISSUE THREAD

**Issue by brakdag** [sindresorhus/speed-test#62]
```shell
 speed-test
       Ping ⠋ 
   Download
     Upload
✖ Error: No server found, verify your proxy/network
    at gotServers (/usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:634:25)
    at /usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:118:16
    at /usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:317:7
    at Parser.<anonymous> (/usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:182:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:314:16)
    at Parser.parseString (/usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:369:19)
    at /usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:315:5
    at /usr/local/nvm/versions/node/v10.14.2/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:118:16
```

**Comment by stefanmck** [comment]
i have the same problem

**Comment by klotzma** [comment]
I also have the problem

**Comment by v8jlene** [comment]
It  looks like the speed test servers list can only be retrieved now if you accept gzip content encoding. After modifying getHttp in speedtest-net to accept gzip and decompress the returned content it is working again here.

**Comment by yumitsu** [comment]
@v8jlene There is no need to modify code in `speedtest-net` - new version with gzip support was released just yesterday.

**Comment by v8jlene** [comment]
> @v8jlene There is no need to modify code in `speedtest-net` - new version with gzip support was released just yesterday.

Ah, yes, I see the update now. It wasn't there last time I checked. Thanks.

**Comment by yumitsu** [comment]
@v8jlene As I found, you can bypass this error this way:
```bash
npm uninstall speed-test -g
npm install speedtest-net@latest -g
npm install speed-test -g
```

After it everything working as expected.

**Comment by brakdag** [comment]
good work, running now,

**Comment by harshit2123** [comment]
Having same error, Any other solution guys??
