### ISSUE TITLE
No server found

### ISSUE THREAD

**Issue by jfoclpf** [sindresorhus/speed-test#74]
I have internet, and yet I get "no server found" error

```
joao@delft:~$ sudo npm install --global speed-test
[sudo] senha para joao: 

added 122 packages, and audited 123 packages in 3s

48 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.1.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.1.2
npm notice Run npm install -g npm@9.1.2 to update!
npm notice 
joao@delft:~$ speed-test

      Ping ⠏ 
  Download   
    Upload   
✖ Error: No server found, verify your proxy/network
    at gotServers (/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)
joao@delft:~$ ping google.com
PING google.com(ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e)) 56 data bytes
64 bytes from ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e): icmp_seq=1 ttl=119 time=3.57 ms
64 bytes from ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e): icmp_seq=2 ttl=119 time=3.36 ms
64 bytes from ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e): icmp_seq=3 ttl=119 time=3.72 ms
64 bytes from ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e): icmp_seq=4 ttl=119 time=3.82 ms
64 bytes from ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e): icmp_seq=5 ttl=119 time=4.08 ms
64 bytes from ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e): icmp_seq=6 ttl=119 time=3.69 ms
64 bytes from ams16s32-in-x0e.1e100.net (2a00:1450:400e:80c::200e): icmp_seq=7 ttl=119 time=3.61 ms
^C
--- google.com ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6009ms
rtt min/avg/max/mdev = 3.361/3.691/4.075/0.205 ms

```

**Comment by Sanix-Darker** [comment]
Same error here : 
```bash
speed-test-v

      Ping ⠏
  Download
    Upload
    Server
  Location
  Distance
✖ Error: No server found, verify your proxy/network
    at gotServers (/home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/dk/.nvm/versions/node/v18.6.0/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)
```

**Comment by ronschd** [comment]
I got a "No Server Found" Error too.
Is there any way to fix that ?


```
speed-test

 Error: No server found, verify your proxy/network
    at gotServers (/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)
```

**Comment by yukha-dw** [comment]
Seems like related issue with this one https://github.com/ddsol/speedtest.net/issues/132#issuecomment-1268726701. I'm not sure how to apply the fix to this package.

**Comment by piemree** [comment]
same error

✖ Error: No server found, verify your proxy/network
    at gotServers (C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\speedtest-net\index.js:649:25)
    at C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\speedtest-net\index.js:119:16
    at C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\speedtest-net\index.js:330:7
    at Parser.<anonymous> (C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\xml2js\lib\parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\xml2js\lib\parser.js:262:26)
    at emit (C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\Users\piemr\AppData\Roaming\npm\node_modules\speed-test\node_modules\sax\lib\sax.js:1436:13)

**Comment by zuomirror** [comment]
Error: No server found, verify your proxy/network
    at gotServers (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:512:28)
    at SAXParser.onclosetag (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)

**Comment by zuomirror** [comment]
Ping ⠏
  Download
    Upload
✖ Error: No server found, verify your proxy/network
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/local/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)

**Comment by papb** [comment]
I have the same issue in Android with Termux

```text
.../MyFiles/TermuxContext $ speed-test -v

      Ping ⠸
  Download
    Upload
    Server
  Location
  Distance
✖ Error: No server found, verify your proxy/network
    at gotServers (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/data/data/com.termux/files/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)

.../MyFiles/TermuxContext $ speed-test --version
3.0.0

.../MyFiles/TermuxContext $ node -v
v18.14.1

.../MyFiles/TermuxContext $ npm -v
9.3.1

.../MyFiles/TermuxContext $ uname -a
Linux localhost 4.14.186+ #1 SMP PREEMPT Tue Feb 28 07:41:48 CST 2023 aarch64 Android
```

**Comment by adibfarrasy** [comment]
I got the same issue
```  
      Ping ⠏ 
  Download   
    Upload   
✖ Error: No server found, verify your proxy/network
    at gotServers (/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)
```

```
❯ speed-test --version
3.0.0
❯ uname -a                               
Linux babysharch 6.3.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000 x86_64 GNU/Linux
```

**Comment by TheFibonacciEffect** [comment]
I got the same issue and made sure that I have installed the npm library : `sudo npm install --global speed-test` as well at that the version matches: 
```
➜  ~ node -v
v20.5.0
```

and still I get
```

➜  ~ speed-test

      Ping ⠸
  Download
    Upload
✖ Error: No server found, verify your proxy/network
    at gotServers (/usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /usr/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:514:28)
    at SAXParser.onclosetag (/usr/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1436:13)
```

**Comment by barisbogdan** [comment]
Same

![Screenshot_20231230-174324_Replit.jpg](https://github.com/sindresorhus/speed-test/assets/125189795/f1d07591-d96d-4a52-9b77-0ed613c00f88)
![Screenshot_20231230-174319_Replit.jpg](https://github.com/sindresorhus/speed-test/assets/125189795/6ae02d1d-89e8-4cfe-a12c-af064fbd6735)
![Screenshot_20231230-172917_Replit.jpg](https://github.com/sindresorhus/speed-test/assets/125189795/ef2dabfd-c30f-473e-a0c5-ce4378d7b663)
![Screenshot_20231230-172923_Replit.jpg](https://github.com/sindresorhus/speed-test/assets/125189795/f34e986c-4d51-4511-9de8-b8f490a222d9)

**Comment by piersolenski** [comment]
same 😿

**Comment by mtuchi** [comment]
Same 
```
 speed-test

      Ping ⠼ 
  Download   
    Upload   
✖ Error: No server found, verify your proxy/network
        at gotServers (/Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:649:25)
    at /Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:119:16
    at /Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:330:7
    at Parser.<anonymous> (/Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:625:35)
    at emitNode (/Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:630:5)
    at closeTag (/Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:890:7)
    at SAXParser.write (/Users/mtuchi/.asdf/installs/nodejs/18.12.1/lib/node_modules/speed-test/node_modules/sax/lib/sax.js:1437:13)
   
 ```

**Comment by q2333gh** [comment]
same~

**Comment by ofarukcaki** [comment]
same

**Comment by bathiatuss** [comment]
![Ekran görüntüsü 2024-08-07 190349](https://github.com/user-attachments/assets/f05da934-e6a1-4e0e-8613-1b456b6682b4)
Same error.
Guys I'am working on a similar project right now. You can check my profile in 3 4 days.
07.08.2024


Edit: mLab-speed-test repository is on my profile guys. You can check it out.

**Comment by dmxt** [comment]
I have same problem.

> ![Ekran görüntüsü 2024-08-07 190349](https://private-user-images.githubusercontent.com/67705822/355892856-f05da934-e6a1-4e0e-8613-1b456b6682b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjI2OTAsIm5iZiI6MTczMTQ2MjM5MCwicGF0aCI6Ii82NzcwNTgyMi8zNTU4OTI4NTYtZjA1ZGE5MzQtZTZhMS00ZTBlLTg2MTMtMWI0NTZiNjY4MmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAxNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDg5NjUzNDc4ZThkNzc1NGU2ODNkMTY4OTIxYTkzZWIxMGNjZDFkODMwNzY4NzUyZDlkNTE2ZjM0ZmQ3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.el_3ShelIjAQRElRlPVYwJF0kfZJJHnt4tcb2GaeQhI) Same error. Guys I'am working on a similar project right now. You can check my profile in 3 4 days. 07.08.2024
> 
> Edit: mLab-speed-test repository is on my profile guys. You can check it out.

Can you upload it to npmjs.com so I can run it with `npx`?

**Comment by tokKurumi** [comment]
same issue here

**Comment by bathiatuss** [comment]
> I have same problem.
> 
> > ![Ekran görüntüsü 2024-08-07 190349](https://private-user-images.githubusercontent.com/67705822/355892856-f05da934-e6a1-4e0e-8613-1b456b6682b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjI2OTAsIm5iZiI6MTczMTQ2MjM5MCwicGF0aCI6Ii82NzcwNTgyMi8zNTU4OTI4NTYtZjA1ZGE5MzQtZTZhMS00ZTBlLTg2MTMtMWI0NTZiNjY4MmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAxNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDg5NjUzNDc4ZThkNzc1NGU2ODNkMTY4OTIxYTkzZWIxMGNjZDFkODMwNzY4NzUyZDlkNTE2ZjM0ZmQ3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.el_3ShelIjAQRElRlPVYwJF0kfZJJHnt4tcb2GaeQhI) Same error. Guys I'am working on a similar project right now. You can check my profile in 3 4 days. 07.08.2024
> > Edit: mLab-speed-test repository is on my profile guys. You can check it out.
> 
> Can you upload it to npmjs.com so I can run it with `npx`?

you can clone the repo [mLab-speedtest-cli](https://github.com/bathiatuss/mLab-speedtest-cli). you can use it with simple commands on terminal. i didn't have time to create a api for devs. Contributions welcome.


<img width="1165" height="575" alt="Image" src="https://github.com/user-attachments/assets/a650eb7c-e3ec-4371-9dc8-2030af4fdda2" />
